unet:
  input_channels: [64, 128, 256, 512]
  # input_shape: [570, 282, 138, 66, 30, 54, 102, 198, 390]
  input_shape: [320, 160, 80, 40, 20]
  num_classes: 2
  image_channels: 3
  dropout: 0.1
  use_ln: True
  padding: 1

train:
  data: 'data'
  batch_size: 10
  scheduler_type: 'warmup-cosine'
  max_epochs: 50
  warmup_epochs: 4
  use_bitsandbytes: True
  optim: 'adamw'
  lr: 1e-4
  device: 'cuda'
  save_path: 'weights'
  eval_epoch: 1
  log_epoch: 1
  save_epoch: 3
  log_path: 'logs'
  early_stopping: 50
  w_0: 1.1
  dataset_name: "pedestrian"

inference:
  checkpoint: 'WEIGHTS-PATH'

overfit_one_batch:
  tolerance: 1e-6
  max_steps: 250
  overfit: False
  hp_search: False
  full_train: True
  logging_steps: 10
