unet:
  input_channels: [64, 128, 256, 512]
  input_shape: [570, 282, 138, 66, 30, 54, 102, 198, 390]
  num_classes: 2
  image_channels: 1
  dropout: 0.1
  use_ln: True

train:
  data: 'data'
  batch_size: 1
  scheduler_type: 'warmup-cosine'
  max_epochs: 50
  warmup_epochs: 10
  use_bitsandbytes: False
  optim: 'adamw'
  lr: 1e-4
  device: 'cpu'
  save_path: 'weights'
  eval_epoch: 1
  log_epoch: 1
  save_epoch: 3
  log_path: 'logs'
  early_stopping: 10
  w_0: 2.0

inference:
  checkpoint: 'weights\unet_49.pth'

overfit_one_batch:
  tolerance: 1e-6
  max_steps: 250
  overfit: True
  hp_search: False
  full_train: True
  logging_steps: 10
